import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './global.css';

import PrelineScript from './components/PrelineScript';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="py-[20px] px-[50px]">
            <div className="flex flex-wrap gap-x-4">
              <Link href="/">Home</Link>
              <Link href="/accordion">Accordion</Link>
              <Link href="/carousel">Carousel</Link>
              <Link href="/collapse">Collapse</Link>
              <Link href="/dropdown">Dropdown</Link>
              <Link href="/input-number">Input Number</Link>
              <Link href="/overlay">Overlay</Link>
              <Link href="/pin-input">Pin Input</Link>
              <Link href="/remove-element">Remove Element</Link>
              <Link href="/scrollspy">Scrollspy</Link>
              <Link href="/select">Select</Link>
              <Link href="/stepper">Stepper</Link>
              <Link href="/strong-password">Strong Password</Link>
              <Link href="/tabs">Tabs</Link>
              <Link href="/toggle-count">Toggle Count</Link>
              <Link href="/toggle-password">Toggle Password</Link>
              <Link href="/tooltip">Tooltip</Link>
            </div>
          </div>
        </header>

        <div className="pb-[20px] px-[50px]">{children}</div>
      </body>

      <PrelineScript />
    </html>
  );
}
